version: 1.0
name: ink-erc20
stages:
  Initialization:
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/tmp/ink-erc20
      - name: template init
        uses: git-checkout
        with:
          url: https://github.com/abing258/ink-erc20.git
          branch: master
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/tmp/polkadot
      - name: frontend init
        uses: git-checkout
        with:
          url: https://github.com/abing258/polkadot-js-apps.git
          branch: master


  Build Contract:
    needs:
      - Initialization
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/tmp/ink-erc20
      - name: Build Contract
        run: |
          cargo +nightly contract build

  Deploy Contract:
    needs:
      - Build Contract
    steps:
      - name: Deploy Contract
        uses: deploy-ink-contract
        with:
          ## network的值有：Local,Rococo,Shibuya,Shiden
          network: Local
          mnemonic: laptop lyrics puppy only conduct frog little test tail atom foil wolf

  Build Front-End:
    needs:
      - Deploy Contract
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/tmp/polkadot
      - name: Build Front-End
        run: |
          yarn install

  Deploy Front-End:
    needs:
      - Build Front-End
    steps:
      - name: Deploy Front-End
        run: |
          if [ -f "polkadot_node.pid" ]; then
            kill -9 `cat polkadot_node.pid`  || (echo 'No such process ')
          fi
          nohup yarn run start > node.log 2>&1& echo $! > polkadot_node.pid
          echo 'frontend url is http://localhost:3000'
          sleep 2